group: travis_latest
language: python
cache: pip
python:
    - 3.6
    #- nightly
    #- pypy3
matrix:
    allow_failures:
        - python: nightly
        - python: pypy3
install:
    - pip install -r requirements.txt
    - pip install flake8  # pytest  # add another testing frameworks later
before_script:
    - flake8 --show-source .
script:
    - pytest
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
